image: alpine:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375/

stages:
  - build
  - test

include:
  - local: '/.gitlab-ci/Jobs/build_image.yml'
  - local: '/.gitlab-ci/Jobs/container_security_scan.yml'
